from pydantic_ai import Agent, RunContext, UsageLimits
from pydantic_ai.models.huggingface import HuggingFaceModel
from pydantic_ai.providers.huggingface import HuggingFaceProvider
from loguru import logger
import sys



logger.remove()
logger.add(sys.stdout, format="{time:YYYY-MM-DD HH:mm:ss.SSS} | {message}")
logger.info("Starting the application...")



pro = HuggingFaceProvider(api_key="REDACTED_HF_KEY")
model = HuggingFaceModel("Qwen/Qwen2.5-7B-Instruct", provider=pro)

# pro = HuggingFaceProvider()

# model = HuggingFaceModel(
#     "HuggingFaceH4/zephyr-7b-beta",
#     provider=pro
# )


logger.info("IFX hosted LLM Model initialized")

joke_selection_agent = Agent(
model, system_prompt=(
    'Use the `joke_factory` to' 
    'generate some jokes, at least 3, then choose the best.'
    'You must return just a single joke.' 
    ),
)
logger. info("Joke selection agent initialized")
joke_generation_agent = Agent(
    model, output_type=list[str]
)
logger. info("Joke generation agent initialized")

@joke_selection_agent.tool
async def joke_factory(ctx: RunContext[None],count: int) -> list[str]:

    print(ctx.usage)

    r = await joke_generation_agent.run(
        f"Please generate {count} jokes.",
        usage_limits=UsageLimits(request_limit=5,total_tokens_limit=600),
        usage=ctx.usage,
    )

    print("\nJoke generated by the agent :\n", r.output, "\n\n")

    return r.output
logger.info("Added Joke Factory tool, which internally utilized joke generation agent")

result=joke_selection_agent.run_sync("Tell me a joke.",
                                     usage_limits=UsageLimits(request_limit=5,total_tokens_limit=700))

logger.info(f"Final joke  :\n{result.output}")